### ISSUE TITLE
Non-functional for multiple videos

### ISSUE THREAD

**Issue by brandleesee** [ink8bit/code-jquery-plugin-show-yt-video#1]
When trying to put multiple videos, the last one is featured on each and every button. An example is in the compressed folder attached.

Can something be done to have a video gallery supported by this plugin?

Thanks.

[showYtvideo-TEST.zip](https://github.com/ink8bit/code-jquery-plugin-show-yt-video/files/82802/showYtvideo-TEST.zip)

**Comment by ink8bit** [comment]
I will check this issue.

**Comment by brandleesee** [comment]
Yes please, in the mean time, I have moved to another part of the website I'm working on so as to allow the most time because I'm too fond of your plugin to change it to another dev's built-in video gallery.
